/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BadgeTest {
        "name"?: string;
        "size"?: string;
    }
}
declare global {
    interface HTMLBadgeTestElement extends Components.BadgeTest, HTMLStencilElement {
    }
    var HTMLBadgeTestElement: {
        prototype: HTMLBadgeTestElement;
        new (): HTMLBadgeTestElement;
    };
    interface HTMLElementTagNameMap {
        "badge-test": HTMLBadgeTestElement;
    }
}
declare namespace LocalJSX {
    interface BadgeTest {
        "name"?: string;
        "size"?: string;
    }
    interface IntrinsicElements {
        "badge-test": BadgeTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "badge-test": LocalJSX.BadgeTest & JSXBase.HTMLAttributes<HTMLBadgeTestElement>;
        }
    }
}
