/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MedBadge {
        "name"?: string;
        "size"?: string;
    }
    interface MedButton {
        "color"?: string;
        "disabled": boolean;
        "expand"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MedProgress {
        "porcentagem"?: string;
    }
}
declare global {
    interface HTMLMedBadgeElement extends Components.MedBadge, HTMLStencilElement {
    }
    var HTMLMedBadgeElement: {
        prototype: HTMLMedBadgeElement;
        new (): HTMLMedBadgeElement;
    };
    interface HTMLMedButtonElement extends Components.MedButton, HTMLStencilElement {
    }
    var HTMLMedButtonElement: {
        prototype: HTMLMedButtonElement;
        new (): HTMLMedButtonElement;
    };
    interface HTMLMedProgressElement extends Components.MedProgress, HTMLStencilElement {
    }
    var HTMLMedProgressElement: {
        prototype: HTMLMedProgressElement;
        new (): HTMLMedProgressElement;
    };
    interface HTMLElementTagNameMap {
        "med-badge": HTMLMedBadgeElement;
        "med-button": HTMLMedButtonElement;
        "med-progress": HTMLMedProgressElement;
    }
}
declare namespace LocalJSX {
    interface MedBadge {
        "name"?: string;
        "size"?: string;
    }
    interface MedButton {
        "color"?: string;
        "disabled"?: boolean;
        "expand"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MedProgress {
        "porcentagem"?: string;
    }
    interface IntrinsicElements {
        "med-badge": MedBadge;
        "med-button": MedButton;
        "med-progress": MedProgress;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "med-badge": LocalJSX.MedBadge & JSXBase.HTMLAttributes<HTMLMedBadgeElement>;
            "med-button": LocalJSX.MedButton & JSXBase.HTMLAttributes<HTMLMedButtonElement>;
            "med-progress": LocalJSX.MedProgress & JSXBase.HTMLAttributes<HTMLMedProgressElement>;
        }
    }
}
