/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BadgeTest {
        "name"?: string;
        "size"?: string;
    }
    interface ProgressBar {
        "porcentagem"?: string;
    }
    interface TestButton {
        "color"?: string;
        "disabled": boolean;
        "expand"?: string;
        "name"?: string;
        "size"?: string;
    }
}
declare global {
    interface HTMLBadgeTestElement extends Components.BadgeTest, HTMLStencilElement {
    }
    var HTMLBadgeTestElement: {
        prototype: HTMLBadgeTestElement;
        new (): HTMLBadgeTestElement;
    };
    interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {
    }
    var HTMLProgressBarElement: {
        prototype: HTMLProgressBarElement;
        new (): HTMLProgressBarElement;
    };
    interface HTMLTestButtonElement extends Components.TestButton, HTMLStencilElement {
    }
    var HTMLTestButtonElement: {
        prototype: HTMLTestButtonElement;
        new (): HTMLTestButtonElement;
    };
    interface HTMLElementTagNameMap {
        "badge-test": HTMLBadgeTestElement;
        "progress-bar": HTMLProgressBarElement;
        "test-button": HTMLTestButtonElement;
    }
}
declare namespace LocalJSX {
    interface BadgeTest {
        "name"?: string;
        "size"?: string;
    }
    interface ProgressBar {
        "porcentagem"?: string;
    }
    interface TestButton {
        "color"?: string;
        "disabled"?: boolean;
        "expand"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface IntrinsicElements {
        "badge-test": BadgeTest;
        "progress-bar": ProgressBar;
        "test-button": TestButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "badge-test": LocalJSX.BadgeTest & JSXBase.HTMLAttributes<HTMLBadgeTestElement>;
            "progress-bar": LocalJSX.ProgressBar & JSXBase.HTMLAttributes<HTMLProgressBarElement>;
            "test-button": LocalJSX.TestButton & JSXBase.HTMLAttributes<HTMLTestButtonElement>;
        }
    }
}
