/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MedBadge {
        "color"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MedButton {
        "color"?: string;
        "disabled": boolean;
        "expand"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MedChartRadial {
        "size"?: string;
        "success"?: string;
        "warning"?: string;
    }
    interface MedDownload {
        "color"?: string;
        "porcentagem"?: string;
        "size"?: string;
        "state"?: string;
    }
    interface MedProgress {
        "color"?: string;
        "porcentagem"?: string;
    }
    interface MedRange {
        "color"?: string;
        "porcentagem"?: string;
    }
}
declare global {
    interface HTMLMedBadgeElement extends Components.MedBadge, HTMLStencilElement {
    }
    var HTMLMedBadgeElement: {
        prototype: HTMLMedBadgeElement;
        new (): HTMLMedBadgeElement;
    };
    interface HTMLMedButtonElement extends Components.MedButton, HTMLStencilElement {
    }
    var HTMLMedButtonElement: {
        prototype: HTMLMedButtonElement;
        new (): HTMLMedButtonElement;
    };
    interface HTMLMedChartRadialElement extends Components.MedChartRadial, HTMLStencilElement {
    }
    var HTMLMedChartRadialElement: {
        prototype: HTMLMedChartRadialElement;
        new (): HTMLMedChartRadialElement;
    };
    interface HTMLMedDownloadElement extends Components.MedDownload, HTMLStencilElement {
    }
    var HTMLMedDownloadElement: {
        prototype: HTMLMedDownloadElement;
        new (): HTMLMedDownloadElement;
    };
    interface HTMLMedProgressElement extends Components.MedProgress, HTMLStencilElement {
    }
    var HTMLMedProgressElement: {
        prototype: HTMLMedProgressElement;
        new (): HTMLMedProgressElement;
    };
    interface HTMLMedRangeElement extends Components.MedRange, HTMLStencilElement {
    }
    var HTMLMedRangeElement: {
        prototype: HTMLMedRangeElement;
        new (): HTMLMedRangeElement;
    };
    interface HTMLElementTagNameMap {
        "med-badge": HTMLMedBadgeElement;
        "med-button": HTMLMedButtonElement;
        "med-chart-radial": HTMLMedChartRadialElement;
        "med-download": HTMLMedDownloadElement;
        "med-progress": HTMLMedProgressElement;
        "med-range": HTMLMedRangeElement;
    }
}
declare namespace LocalJSX {
    interface MedBadge {
        "color"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MedButton {
        "color"?: string;
        "disabled"?: boolean;
        "expand"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MedChartRadial {
        "size"?: string;
        "success"?: string;
        "warning"?: string;
    }
    interface MedDownload {
        "color"?: string;
        "porcentagem"?: string;
        "size"?: string;
        "state"?: string;
    }
    interface MedProgress {
        "color"?: string;
        "porcentagem"?: string;
    }
    interface MedRange {
        "color"?: string;
        "porcentagem"?: string;
    }
    interface IntrinsicElements {
        "med-badge": MedBadge;
        "med-button": MedButton;
        "med-chart-radial": MedChartRadial;
        "med-download": MedDownload;
        "med-progress": MedProgress;
        "med-range": MedRange;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "med-badge": LocalJSX.MedBadge & JSXBase.HTMLAttributes<HTMLMedBadgeElement>;
            "med-button": LocalJSX.MedButton & JSXBase.HTMLAttributes<HTMLMedButtonElement>;
            "med-chart-radial": LocalJSX.MedChartRadial & JSXBase.HTMLAttributes<HTMLMedChartRadialElement>;
            "med-download": LocalJSX.MedDownload & JSXBase.HTMLAttributes<HTMLMedDownloadElement>;
            "med-progress": LocalJSX.MedProgress & JSXBase.HTMLAttributes<HTMLMedProgressElement>;
            "med-range": LocalJSX.MedRange & JSXBase.HTMLAttributes<HTMLMedRangeElement>;
        }
    }
}
